import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { dbConnection } from "@/services/mongo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnection();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <main class="py-8">{children}</main>
      </body>
    </html>
  );
}
